---
title: "PS270 Final Project"
author: "Grace Williams"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to childcare.

## Tentative research question

My research question is: How does gender relate to U.S. adults’ intentions or feelings about having children among those who have never been parents? I want to find out if women and men differ in how they describe their thoughts about having children. My hypothesis is that women are more likely than men to say that they “never wanted to have children” or “weren’t sure” compared to men, reflecting social and behavioral patterns in intention of raising kids. The key independent variable is F_GENDER, which indicates whether the respondent self-reported as a woman, a man, in some other way, or refused to answer. The dependent variable is the survey question (KIDSEVER_W147): “Which of the following best describes your thoughts on having children?” with response options: "There was a time when you wanted to have children," "You never wanted to have children," "You weren’t sure whether or not you wanted to have children," and "Refused." My hypothesis would be supported if the responses differ significantly by gender, specifically if women were more likely to respond with "You never wanted to have children" and "You weren’t sure whether or not you wanted to have children." The hypothesis would be disproved if there is no difference by gender, or if men are more likely than women to report they never wanted children or were unsure.

## Data
```{r}
library(tidyverse)

panel_data <- read_csv("ATP W147.csv")
head(panel_data)

clean_data <- panel_data |>
  select(F_GENDER, KIDSEVER_W147) |>
  rename(
    gender = F_GENDER,
    child_views = KIDSEVER_W147
  ) |>
  filter(gender %in% c(1, 2)) |>
  filter(!is.na(child_views)) |>
  filter(child_views != "Refused") |>
  mutate(
    gender = factor(gender, labels = c("Male", "Female")),
    child_views = factor(child_views,
      levels = c(1, 2, 3),
      labels = c(
        "Wanted children at one point",
        "Never wanted children",
        "Unsure")))

ggplot(data = clean_data, mapping = aes(x = child_views, fill = gender)) +
  geom_bar(position = "dodge") +
  labs(
    title = "Views on Having Children by Gender",
    subtitle = "Among U.S. adults who have never had children",
    x = "Response",
    y = "Number of respondents",
    fill = "Gender",
    caption = "Source: Pew Research Center ATP Wave 147"
  )
```

